// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFile = "tb_file"

// File mapped from table <tb_file>
type File struct {
	ID       int32  `gorm:"column:id;primaryKey" json:"id"`
	UserID   int32  `gorm:"column:user_id" json:"user_id"`
	ParentID int32  `gorm:"column:parent_id" json:"parent_id"`
	Name     string `gorm:"column:name" json:"name"`
	Size     int32  `gorm:"column:size" json:"size"`
	Type     string `gorm:"column:type" json:"type"`
	VerNum   int32  `gorm:"column:ver_num" json:"ver_num"`
	StoreKey string `gorm:"column:store_key" json:"store_key"`
	Ctime    int32  `gorm:"column:ctime" json:"ctime"`
	Mtime    int32  `gorm:"column:mtime" json:"mtime"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
