// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSession = "tb_session"

// Session mapped from table <tb_session>
type Session struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id"`
	UserID    int32  `gorm:"column:user_id" json:"user_id"`
	SessionID string `gorm:"column:session_id" json:"session_id"`
	Ctime     int32  `gorm:"column:ctime" json:"ctime"`
	Etime     int32  `gorm:"column:etime" json:"etime"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
