// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVersion = "tb_version"

// Version mapped from table <tb_version>
type Version struct {
	ID       int32  `gorm:"column:id;primaryKey" json:"id"`
	FileID   int32  `gorm:"column:file_id" json:"file_id"`
	Size     int32  `gorm:"column:size" json:"size"`
	VerNum   int32  `gorm:"column:ver_num" json:"ver_num"`
	StoreKey string `gorm:"column:store_key" json:"store_key"`
	Ctime    int32  `gorm:"column:ctime" json:"ctime"`
}

// TableName Version's table name
func (*Version) TableName() string {
	return TableNameVersion
}
